---
- name: Copy "minecraft.service" to etc/systemd/system
  copy:
    src: /mcserver/minecraft.service
    dest: /etc/systemd/system
  notify: start minecraft.service

- name: Copy "minecraftfailure.service" to etc/systemd/system
  copy:
    src: /mcserver/minecraftfailure.service
    dest: /etc/systemd/system
  notify: reload systemd

- name: Cron entry to Backup and Restart Minecraft server.
  cron:
    name: "backup-restart"
    minute: "0"
    hour: "12"
    job: "bash /opt/mcserver/mccmd backup-restart > /opt/mcserver/systemlogs.txt 2>&1"

- name: Cron entry to check if server is available.
  cron:
    name: "port-check-restart"
    minute: "*/10"
    job: "bash /opt/mcserver/mccmd port-check-restart"

- name: Cron entry to clean backups and move to longterm.
  cron:
    name: "clean-backups"
    minute: "0"
    hour: "0"
    day: "1"
    job: "bash /opt/mcserver/mccmd clean-backups > /opt/mcserver/systemlogs.txt 2>&1"

- name: Cron entry to create a world backup while running with rdiff.
  cron:
    name: "running-backup"
    minute: "5"
    hour: "*/1"
    user: mc
    job: "bash /opt/mcserver/mccmd running-backup > /opt/mcserver/systemlogs.txt 2>&1"
