---
- name: Setup Minecraft Server.
  hosts: mcsv
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt:
        update_cache: true
        cache_valid_time: 3600

  handlers:
    - name: start minecraft service
      service:
        name: minecraft
        state: restarted
        enabled: true

    - name: systemd reload
      systemd:
        daemon_reload: true

    - name: restart mcserver
      command: /opt/mcserver/mccmd fast-restart

  tasks:
    - name: Install Java.
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Screen.
      apt:
        name: screen
        state: present

    - name: Install rdiff-backup.
      apt:
        name: rdiff-backup
        state: present

    - name: Open port 25565 for minecraft.
      ufw:
        rule: allow
        port: "25565"

    - name: Have Group "mc".
      group:
        name: mc
        state: present

    - name: Have User "mc".
      user:
        name: mc
        state: present
        group: mc

    - name: Have "mcserver" folder present, permissions.
      file:
        path: /opt/mcserver
        state: directory
        owner: mc
        group: mc
        mode: "0775"

    - name: Have "logs" folder present, permissions.
      file:
        path: /opt/mcserver/logs
        state: directory
        owner: mc
        group: mc
        mode: "0775"

    - name: Have "backupslongterm" folder present, permissions.
      file:
        path: /opt/mcserver/backupslongterm
        state: directory
        owner: mc
        group: mc
        mode: "0775"

    - name: Have "fullbackupstaging" folder present, permissions.
      file:
        path: /opt/mcserver/fullbackupstaging
        state: directory
        owner: mc
        group: mc
        mode: "0775"

    - name: Have "rdiffbackups" folder present, permissions.
      file:
        path: /opt/mcserver/rdiffbackups
        state: directory
        owner: mc
        group: mc
        mode: "0775"

    - name: Copy Server Files.
      copy:
        src: ~/mcserver/foxxolay
        dest: /opt/mcserver/foxxolay
        owner: mc
        group: mc
        mode: "0775"
      notify: restart mcserver

    - name: Copy Command File.
      copy:
        src: /mcserver/mccmd
        dest: /opt/mcserver/mccmd
        owner: mc
        group: mc
        mode: a+x

    - name: Copy "minecraft.service" to etc/systemd/system
      copy:
        src: /mcserver/minecraft.service
        dest: /etc/systemd/system
      notify: start minecraft.service

    - name: Copy "minecraftfailure.service" to etc/systemd/system
      copy:
        src: /mcserver/minecraftfailure.service
        dest: /etc/systemd/system
      notify: reload systemd

    - name: Cron entry to Backup and Restart Minecraft server.
      cron:
        name: "backup-restart"
        minute: "0"
        hour: "12"
        job: "bash /opt/mcserver/mccmd backup-restart > /opt/mcserver/systemlogs.txt 2>&1"

    - name: Cron entry to check if server is available.
      cron:
        name: "port-check-restart"
        minute: "*/10"
        job: "bash /opt/mcserver/mccmd port-check-restart"

    - name: Cron entry to clean backups and move to longterm.
      cron:
        name: "clean-backups"
        minute: "0"
        hour: "0"
        day: "1"
        job: "bash /opt/mcserver/mccmd clean-backups > /opt/mcserver/systemlogs.txt 2>&1"

    - name: Cron entry to create a world backup while running with rdiff.
      cron:
        name: "running-backup"
        minute: "5"
        hour: "*/1"
        user: mc
        job: "bash /opt/mcserver/mccmd running-backup > /opt/mcserver/systemlogs.txt 2>&1"
