---
- name: Install Java.
  apt:
    name: openjdk-17-jdk
    state: present

- name: Install Screen.
  apt:
    name: screen
    state: present

- name: Install rdiff-backup.
  apt:
    name: rdiff-backup
    state: present
