---
- name: Open port 25565 for minecraft.
  ufw:
    rule: allow
    port: "25565"

- name: Open port 24454 for simple voice chat.
  ufw:
    rule: allow
    port: "24454"
    proto: "udp"

- name: Have Group "mc".
  group:
    name: mc
    state: present

- name: Have User "mc".
  user:
    name: mc
    state: present
    group: mc
    shell: /bin/bash

- name: Timezone EST
  timezone:
    name: America/New_York
